packages:
  - 'packages/*'
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  esbuild: true
  prisma: true
pnpm:
  onlyBuiltDependencies:
    - '@prisma/client'
    - '@prisma/engines'
    - bcryptjs
    - esbuild
    - prisma
